controller_manager_ns: controller_manager
controller_list:
  - name: hello_ros_robot/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - hip
      - shoulder
      - elbow
      - wrist
