hello_ros_robot:
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: 
     - hip
     - shoulder
     - elbow
     - wrist
    
    gains:
      hip:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      shoulder:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      elbow:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      wrist:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      
