<?xml version="1.0"?>
<!-- =================================================================================== -->
<!-- |    DTU Ecocar URDF (Dynamo)                                                     | -->
<!-- |    Notes: body mass and wheel mass are not the actual values (but close)        | -->
<!-- |    Coordinate system has x = 0 between rear wheels with x forward               | -->
<!-- |    Author: Thomas Passer Jensen (s134234@student.dtu.dk)                        | -->
<!-- =================================================================================== -->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ecocar">
  <!-- Parameters -->

  <xacro:include filename="params.xacro" />

  <!-- These parameters do not represent real world values but determine the internal steering PID regulator-->
  <xacro:property name="steer_joint_damping" value="0.1" />
  <xacro:property name="steer_joint_friction" value="0" />

  <!-- Begin Gazebo definitions -->

  <xacro:include filename="ecocar.gazebo" />
  <!-- End Gazebo definitions -->

  <link name="base_link">
    <inertial>
      <origin rpy="0 0 0" xyz="${wheelbase/2-wheel_mid_offset} 0 ${body_above_ground}"/> <!-- + height/2, but need to fix COG then.. -->
      <mass value="${body_mass}"/>
      <inertia ixx="${body_mass/12 * (width**2 + height**2)}" ixy="0.0" ixz="0.0" iyy="${body_mass/12 * (length**2 + height**2)}" iyz="0.0" izz="${body_mass/12 * (width**2 + length**2)}"/>
    </inertial>

    <visual>
      <origin rpy="0 0 ${-pi/2}" xyz="${wheelbase/2-wheel_mid_offset} 0 ${body_above_ground}"/>
      <geometry>
        <mesh filename="package://ecocar_description/meshes/ecocar16.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 ${-pi/2}" xyz="${wheelbase/2-wheel_mid_offset} 0 ${body_above_ground}" />
      <geometry>
        <mesh filename="package://ecocar_description/meshes/ecocar16.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>

  <link name="rear_left_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_mass/12 * (3*wheel_radius**2 + wheel_width**2)}" ixy="0.0" ixz="0.0" iyy="${wheel_mass/12 * (3*wheel_radius**2 + wheel_width**2)}" iyz="0.0" izz="${0.5*wheel_mass*wheel_radius**2}"/>
    </inertial>
    <visual>
      <origin rpy="0 ${pi/2} 0" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://ecocar_description/meshes/wheel_meshlab.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
  </link>

  <link name="rear_right_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_mass/12 * (3*wheel_radius**2 + wheel_width**2)}" ixy="0.0" ixz="0.0" iyy="${wheel_mass/12 * (3*wheel_radius**2 + wheel_width**2)}" iyz="0.0" izz="${0.5*wheel_mass*wheel_radius**2}"/>
    </inertial>
    <visual>
      <origin rpy="0 ${-pi/2} 0" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://ecocar_description/meshes/wheel_meshlab.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
  </link>

  <joint name="base_to_wheel_rear_left" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 ${rear_track_width/2} ${wheel_radius}" rpy="${-pi/2} 0 0" />
    <dynamics damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
  </joint>

  <joint name="base_to_wheel_rear_right" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 ${-rear_track_width/2} ${wheel_radius}" rpy="${-pi/2} 0 0" />
    <dynamics damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
  </joint>



  <link name="front_left_axle">
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.004" ixy="0.0" ixz="0.0" iyy="0.004" iyz="0.0" izz="0.004"/>
    </inertial>
  </link>

  <link name="front_right_axle">
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.004" ixy="0.0" ixz="0.0" iyy="0.004" iyz="0.0" izz="0.004"/>
    </inertial>
  </link>

  <link name="front_left_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_mass/12 * (3*wheel_radius**2 + wheel_width**2)}" ixy="0.0" ixz="0.0" iyy="${wheel_mass/12 * (3*wheel_radius**2 + wheel_width**2)}" iyz="0.0" izz="${0.5*wheel_mass*wheel_radius**2}"/>
    </inertial>
    <visual>
      <origin rpy="0 ${pi/2} 0" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://ecocar_description/meshes/wheel_meshlab.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
  </link>

  <link name="front_right_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_mass/12 * (3*wheel_radius**2 + wheel_width**2)}" ixy="0.0" ixz="0.0" iyy="${wheel_mass/12 * (3*wheel_radius**2 + wheel_width**2)}" iyz="0.0" izz="${0.5*wheel_mass*wheel_radius**2}"/>
    </inertial>
    <visual>
      <origin rpy="0 ${pi/2} 0" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://ecocar_description/meshes/wheel_meshlab.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
  </link>

  <joint name="front_left_steer_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_axle"/>
    <origin xyz="${wheelbase} ${front_track_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi*max_turn/180}" upper="${pi*max_turn/180}" effort="10000000" velocity="1000000"/>
    <dynamics damping="${steer_joint_damping}" friction="${steer_joint_friction}"/>
  </joint>

  <joint name="front_right_steer_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_axle"/>
    <origin xyz="${wheelbase} ${-front_track_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi*max_turn/180}" upper="${pi*max_turn/180}" effort="10000000" velocity="1000000"/>
    <dynamics damping="${steer_joint_damping}" friction="${steer_joint_friction}"/>
  </joint>


  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="front_left_axle"/>
    <child link="front_left_wheel"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
    <axis xyz="0 0 1"/>
    <dynamics damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
  </joint>

  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="front_right_axle"/>
    <child link="front_right_wheel"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
    <axis xyz="0 0 1"/>
    <dynamics damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
  </joint>

  <!-- Sensors -->
  <!-- Camera -->
  <!-- Set position on line beginning with <origin -->
  <link name="camera_link">
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>
  </link>
  <joint name="camera_joint" type="fixed">
  <parent link="base_link"/>
  <child link="camera_link"/>
  <origin xyz="${wheelbase/2} 0 1.10" rpy="0 0 0"/>
</joint>

<!-- Velodyne VLP-16 LiDAR -->
<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
  <VLP-16 parent="base_link" name="velodyne" topic="/sim/velodyne_points" hz="${velodyne_lidar_frequency}" samples="${velodyne_lidar_samples}">
    <origin xyz="${wheelbase/2} 0 ${1.10-0.03585}" rpy="0 0 0" /> <!-- Distance from ground to middle of lidar is 110 cm. It is 71.7 mm tall -->
  </VLP-16>

<!-- Sonar, front -->
<link name="front_sonar_link">
  <inertial>
    <mass value="0.050"/>
    <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
  </inertial>
  <visual>
    <origin rpy="0 ${pi/2} 0" xyz="0 0 0" />
    <geometry>
      <mesh filename="package://ecocar_description/meshes/XL-MaxSonar-WR.stl" scale="0.0254 0.0254 0.0254"/>
    </geometry>
  </visual>
</link>
<joint name="front_sonar_joint" type="fixed">
  <parent link="base_link"/>
  <child link="front_sonar_link"/>
  <origin xyz="${wheelbase/2-wheel_mid_offset+length/2-sonar_offset} 0 ${body_above_ground+0.45}" rpy="0 0 0"/>
</joint>

<!-- LiDAR Lite, Left -->
<!-- Set parameters -->
<!-- Not used ATM
<link name="left_laser_link">
  <inertial>
    <mass value="1"/>
    <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
  </inertial>
  <visual>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
  </visual>
</link>
<joint name="left_laser_joint" type="fixed">
  <parent link="base_link"/>
  <child link="left_laser_link"/>
  <origin xyz="${wheelbase/2} ${width/2} ${body_above_ground+0.1}" rpy="0 0 ${pi/2}"/>
</joint>
-->

<!-- LiDAR Lite, Right -->
<!-- Set parameters -->
<!--
<link name="right_laser_link">
  <inertial>
    <mass value="1"/>
    <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
  </inertial>
  <visual>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
  </visual>
</link>
<joint name="right_laser_joint" type="fixed">
  <parent link="base_link"/>
  <child link="right_laser_link"/>
  <origin xyz="${wheelbase/2} ${-width/2} ${body_above_ground+0.1}" rpy="0 0 ${-pi/2}"/>
</joint>
-->

</robot>
